// packages/app3/src/components/Counter.vue
<template>
	<div>
		<h1>vue app3</h1>
		<h2 id="local_counter">Local Counter {{ counter }}</h2>
		<h2 id="cross_counter">Cross Counter {{ crossCounter }}</h2>
		<div class="action">
			<ui-button id="incrementBtn" @click="increment()">increment</ui-button>
			<ui-button id="incrementCrossBtn" @click="incrementCross">increment cross</ui-button>
		</div>
	</div>
</template>

<script lang="ts">
import store from "../store";
import { Prop, Options, Watch } from "vue-property-decorator";
import { Vue } from "vue-class-component";
import { CrossEventDistributor } from "@xotoboil-multifront-singlespa/cross";

import { UiButton } from "@xotoboil-multifront-singlespa/ui-vue";

@Options({ name: "Counter", components: { UiButton } })
export default class Counter extends Vue {
	@Prop()
	crossEventDistributor!: CrossEventDistributor;

	crossCounter = 0;

	get counter() {
		return store.state.counter;
	}

	increment() {
		store.dispatch("counterIncrement");
	}

	created(): void {
		this.crossCounter = this.crossEventDistributor.crossStore.counter;
		this.crossEventDistributor.on("increment", () => {
			this.crossCounter = this.crossEventDistributor.crossStore.counter;
		});
	}

	incrementCross() {
		if (this.crossEventDistributor) {
			this.crossEventDistributor.crossStore.counter += 1;
			this.crossEventDistributor.emit("increment");
		}
	}
}
</script>

// packages/app2/src/components/counter/Counter.tsx
import React, { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { UiButton } from "@xotoboil-multifront-singlespa/ui-react";
import { CounterModel } from "@/models/CounterModel";
import store, { getCrossEventDistributer } from "@/store";
import { crossEventDistributor } from "@/index";

export const Counter: any = (props: any): JSX.Element => {
	const localCounter = useSelector((state: CounterModel) => state.counter.counter);
	const [crossEventDistributerCounter, setCrossEventDistributerCounterState] = useState(getCrossEventDistributer() ? getCrossEventDistributer().crossStore.counter : 0);
	const setCrossEventDistributerCounter = (value: number) => {
		if (getCrossEventDistributer()?.crossStore) {
			getCrossEventDistributer().crossStore.counter = value;
			crossEventDistributor.emit("increment");
		}
	};
	useEffect(() => {
		let active = true;
		crossEventDistributor.on("increment", () => {
			if (active) setCrossEventDistributerCounterState(getCrossEventDistributer()?.crossStore?.counter);
		});

		return () => {
			active = false;
		};
	}, []);

	return (
		<div>
			<h2 data-testid="local_counter">Local Counter: {localCounter}</h2>
			<h2 data-testid="cross_counter">Cross Counter: {crossEventDistributerCounter}</h2>
			<div className="action">
				<UiButton
					onClick={() => {
						store.dispatch({ type: "counter/counterIncrement" });
					}}
				>
					increment
				</UiButton>
				<UiButton onClick={() => setCrossEventDistributerCounter(crossEventDistributerCounter + 1)}>increment cross</UiButton>
			</div>
		</div>
	);
};
